import { SQLiteDatabase } from 'expo-sqlite';

// Data files generated by scripts/generate_data.py
// Run that script once after downloading the 3 JSON files from the claude.ai session
// Until then the app seeds with a small built-in sample so it can run in development

// ── Small built-in sample (always available) ───────────────────────────────
const SAMPLE_HOSE_FITTINGS = [
  {fitting_type:'Male JIC 37 - Rigid',standard:'JIC',gender:'male',orientation:'rigid',
   end_style:'standard',thread_inch:'9/16x18',hose_id_inch:'5/16',
   dim_A_inch:2.12,dim_H_inch:0.75,dim_B_inch:1.26,dim_E_inch:null,dim_W_inch:null,dim_C_inch:null,dim_D_inch:null},
  {fitting_type:'Male JIC 37 - Rigid',standard:'JIC',gender:'male',orientation:'rigid',
   end_style:'standard',thread_inch:'3/4x16',hose_id_inch:'1/2',
   dim_A_inch:2.35,dim_H_inch:0.875,dim_B_inch:1.36,dim_E_inch:null,dim_W_inch:null,dim_C_inch:null,dim_D_inch:null},
  {fitting_type:'Female JIC 37 - Swivel',standard:'JIC',gender:'female',orientation:'swivel',
   end_style:'standard',thread_inch:'9/16x18',hose_id_inch:'5/16',
   dim_A_inch:1.81,dim_H_inch:null,dim_B_inch:0.95,dim_E_inch:null,dim_W_inch:0.6875,dim_C_inch:null,dim_D_inch:null},
  {fitting_type:'Female JIC 37 - Swivel - 90 Elbow',standard:'JIC',gender:'female',orientation:'elbow',
   end_style:'short_drop',thread_inch:'9/16x18',hose_id_inch:'5/16',
   dim_A_inch:2.15,dim_H_inch:null,dim_B_inch:1.29,dim_E_inch:0.91,dim_W_inch:0.6875,dim_C_inch:null,dim_D_inch:null},
  {fitting_type:'Male Seal-Lok - Rigid - (with O-Ring)',standard:'ORFS',gender:'male',orientation:'rigid',
   end_style:'standard',thread_inch:'11/16x16',hose_id_inch:'3/8',
   dim_A_inch:1.95,dim_H_inch:0.75,dim_B_inch:1.10,dim_E_inch:null,dim_W_inch:null,dim_C_inch:null,dim_D_inch:null},
  {fitting_type:'Female Seal-Lok - Swivel - Short',standard:'ORFS',gender:'female',orientation:'swivel',
   end_style:'standard',thread_inch:'11/16x16',hose_id_inch:'3/8',
   dim_A_inch:1.70,dim_H_inch:null,dim_B_inch:0.84,dim_E_inch:null,dim_W_inch:0.6875,dim_C_inch:0.34,dim_D_inch:null},
  {fitting_type:'Male NPTF Pipe - Rigid',standard:'NPTF',gender:'male',orientation:'rigid',
   end_style:'standard',thread_inch:'1/4x18',hose_id_inch:'3/16',
   dim_A_inch:1.88,dim_H_inch:0.5625,dim_B_inch:1.01,dim_E_inch:null,dim_W_inch:null,dim_C_inch:null,dim_D_inch:null},
  {fitting_type:'Male NPTF Pipe - Rigid',standard:'NPTF',gender:'male',orientation:'rigid',
   end_style:'standard',thread_inch:'3/8x18',hose_id_inch:'5/16',
   dim_A_inch:1.89,dim_H_inch:0.6875,dim_B_inch:1.03,dim_E_inch:null,dim_W_inch:null,dim_C_inch:null,dim_D_inch:null},
  {fitting_type:'Male SAE 45 - Rigid',standard:'SAE45',gender:'male',orientation:'rigid',
   end_style:'standard',thread_inch:'7/16x20',hose_id_inch:'3/16',
   dim_A_inch:1.97,dim_H_inch:0.5,dim_B_inch:1.18,dim_E_inch:null,dim_W_inch:null,dim_C_inch:null,dim_D_inch:null},
  {fitting_type:'Male BSP Parallel Pipe - Rigid - (60 Cone)',standard:'BSPP',gender:'male',
   orientation:'rigid',end_style:'standard',thread_inch:'G 1/4',hose_id_inch:'5/16',
   dim_A_inch:2.12,dim_H_inch:0.75,dim_B_inch:1.15,dim_E_inch:null,dim_W_inch:null,dim_C_inch:null,dim_D_inch:null},
];

const SAMPLE_TUBE_FITTINGS = [
  {fitting_type:'Straight Male Stud',series:'L',series_desc:'L — Light series (max 400 bar)',
   thread_standard:'BSPP',tube_od_mm:6,pressure_rating_bar:400,thread_size:'G 1/4',
   dim_T_mm:4,dim_D2_mm:12,dim_i_mm:29,dim_L_mm:37,dim_L1_mm:10,dim_L2_mm:19,dim_S1_mm:14,dim_S2_mm:35,torque_Nm:4.3},
  {fitting_type:'Straight Male Stud',series:'L',series_desc:'L — Light series (max 400 bar)',
   thread_standard:'BSPP',tube_od_mm:8,pressure_rating_bar:400,thread_size:'G 1/4',
   dim_T_mm:6,dim_D2_mm:12,dim_i_mm:29,dim_L_mm:37,dim_L1_mm:10,dim_L2_mm:19,dim_S1_mm:17,dim_S2_mm:35,torque_Nm:4.7},
  {fitting_type:'Straight Male Stud',series:'L',series_desc:'L — Light series (max 400 bar)',
   thread_standard:'BSPP',tube_od_mm:10,pressure_rating_bar:400,thread_size:'G 3/8',
   dim_T_mm:8,dim_D2_mm:12,dim_i_mm:31.5,dim_L_mm:39.5,dim_L1_mm:12.5,dim_L2_mm:22,dim_S1_mm:19,dim_S2_mm:70,torque_Nm:6.8},
  {fitting_type:'Straight Male Stud',series:'S',series_desc:'S — Heavy series (max 630 bar)',
   thread_standard:'BSPP',tube_od_mm:6,pressure_rating_bar:630,thread_size:'G 1/4',
   dim_T_mm:4,dim_D2_mm:12,dim_i_mm:32,dim_L_mm:40,dim_L1_mm:13,dim_L2_mm:19,dim_S1_mm:17,dim_S2_mm:55,torque_Nm:5.8},
  {fitting_type:'Straight Male Stud',series:'S',series_desc:'S — Heavy series (max 630 bar)',
   thread_standard:'BSPP',tube_od_mm:10,pressure_rating_bar:630,thread_size:'G 3/8',
   dim_T_mm:7,dim_D2_mm:12,dim_i_mm:34.5,dim_L_mm:43.5,dim_L1_mm:15,dim_L2_mm:22,dim_S1_mm:22,dim_S2_mm:90,torque_Nm:9.5},
];

const SAMPLE_HOSES = [
  {hose_name:'SAE 100R1AT / EN 853 1SN — 1 wire braid',reinforcement:'1 wire braid',
   tube_material:'oil resistant synthetic rubber',temp_range:'-40°C to +100°C',
   application:'High pressure hydraulic lines, fuel oil, antifreeze solutions',
   dash_size:-6,id_mm:10,id_inch:'3/8',od_mm:17.4,wp_bar:180,wp_psi:2610,bp_bar:720,bp_psi:10440,min_bend_radius_mm:130,safety_factor:4.0},
  {hose_name:'SAE 100R1AT / EN 853 1SN — 1 wire braid',reinforcement:'1 wire braid',
   tube_material:'oil resistant synthetic rubber',temp_range:'-40°C to +100°C',
   application:'High pressure hydraulic lines, fuel oil, antifreeze solutions',
   dash_size:-8,id_mm:13,id_inch:'1/2',od_mm:20.6,wp_bar:160,wp_psi:2320,bp_bar:640,bp_psi:9280,min_bend_radius_mm:180,safety_factor:4.0},
  {hose_name:'SAE 100R2AT / EN 853 2SN — 2 wire braid',reinforcement:'2 wire braid',
   tube_material:'oil resistant synthetic rubber',temp_range:'-40°C to +100°C',
   application:'High pressure hydraulic lines, fuel oil, antifreeze solutions',
   dash_size:-6,id_mm:10,id_inch:'3/8',od_mm:19.0,wp_bar:275,wp_psi:4000,bp_bar:1100,bp_psi:16000,min_bend_radius_mm:130,safety_factor:4.0},
  {hose_name:'SAE 100R2AT / EN 853 2SN — 2 wire braid',reinforcement:'2 wire braid',
   tube_material:'oil resistant synthetic rubber',temp_range:'-40°C to +100°C',
   application:'High pressure hydraulic lines, fuel oil, antifreeze solutions',
   dash_size:-8,id_mm:13,id_inch:'1/2',od_mm:23.0,wp_bar:250,wp_psi:3625,bp_bar:1000,bp_psi:14500,min_bend_radius_mm:180,safety_factor:4.0},
  {hose_name:'SAE 100R12 / EN 856 4SH — 4 wire spiral heavy',reinforcement:'4 wire spiral',
   tube_material:'oil resistant synthetic rubber',temp_range:'-40°C to +100°C',
   application:'Very high pressure hydraulic lines on mobile and offshore equipment',
   dash_size:-8,id_mm:13,id_inch:'1/2',od_mm:24.6,wp_bar:420,wp_psi:6000,bp_bar:1680,bp_psi:24000,min_bend_radius_mm:230,safety_factor:4.0},
];

// ── Try to load full data files if they exist ──────────────────────────────
// These are generated by scripts/generate_data.py
// If not yet generated, falls back to sample data above
let ALL_HOSE_FITTINGS: any[] = SAMPLE_HOSE_FITTINGS;
let ALL_TUBE_FITTINGS: any[] = SAMPLE_TUBE_FITTINGS;
let ALL_HOSES: any[]         = SAMPLE_HOSES;

try {
  const { HOSE_FITTINGS_0 } = require('./data/hose_fittings_0');
  const { HOSE_FITTINGS_1 } = require('./data/hose_fittings_1');
  const { HOSE_FITTINGS_2 } = require('./data/hose_fittings_2');
  const { HOSE_FITTINGS_3 } = require('./data/hose_fittings_3');
  const { HOSE_FITTINGS_4 } = require('./data/hose_fittings_4');
  const { HOSE_FITTINGS_5 } = require('./data/hose_fittings_5');
  const { HOSE_FITTINGS_6 } = require('./data/hose_fittings_6');
  const { HOSE_FITTINGS_7 } = require('./data/hose_fittings_7');
  const { TUBE_FITTINGS }   = require('./data/tube_fittings');
  const { HOSES }           = require('./data/hoses');
  ALL_HOSE_FITTINGS = [
    ...HOSE_FITTINGS_0,...HOSE_FITTINGS_1,...HOSE_FITTINGS_2,...HOSE_FITTINGS_3,
    ...HOSE_FITTINGS_4,...HOSE_FITTINGS_5,...HOSE_FITTINGS_6,...HOSE_FITTINGS_7,
  ];
  ALL_TUBE_FITTINGS = [...TUBE_FITTINGS];
  ALL_HOSES         = [...HOSES];
} catch {
  // Data files not yet generated — using sample data
  console.log('HydroFit: using sample data. Run scripts/generate_data.py for full dataset.');
}

// ── Seed functions ─────────────────────────────────────────────────────────

export async function seedDatabase(db: SQLiteDatabase): Promise<void> {
  await db.withTransactionAsync(async () => {
    const hfSql = `INSERT INTO hose_fittings
      (fitting_type,standard,gender,orientation,end_style,
       thread_inch,hose_id_inch,dim_A_inch,dim_H_inch,dim_B_inch,
       dim_E_inch,dim_W_inch,dim_C_inch,dim_D_inch)
      VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)`;

    for (const f of ALL_HOSE_FITTINGS) {
      await db.runAsync(hfSql, [
        f.fitting_type, f.standard, f.gender??null, f.orientation??null,
        f.end_style??null, f.thread_inch??null, f.hose_id_inch??null,
        f.dim_A_inch??null, f.dim_H_inch??null, f.dim_B_inch??null,
        f.dim_E_inch??null, f.dim_W_inch??null, f.dim_C_inch??null, f.dim_D_inch??null,
      ]);
    }

    const tfSql = `INSERT INTO tube_fittings
      (fitting_type,series,series_desc,thread_standard,
       tube_od_mm,pressure_rating_bar,thread_size,
       dim_T_mm,dim_D2_mm,dim_i_mm,dim_L_mm,
       dim_L1_mm,dim_L2_mm,dim_S1_mm,dim_S2_mm,torque_Nm)
      VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`;

    for (const t of ALL_TUBE_FITTINGS) {
      await db.runAsync(tfSql, [
        t.fitting_type, t.series, t.series_desc??null, t.thread_standard??null,
        t.tube_od_mm??null, t.pressure_rating_bar??null, t.thread_size??null,
        t.dim_T_mm??null, t.dim_D2_mm??null, t.dim_i_mm??null,
        t.dim_L_mm??null, t.dim_L1_mm??null, t.dim_L2_mm??null,
        t.dim_S1_mm??null, t.dim_S2_mm??null, t.torque_Nm??null,
      ]);
    }

    const hoSql = `INSERT INTO hoses
      (hose_name,reinforcement,tube_material,temp_range,application,
       dash_size,id_mm,id_inch,od_mm,wp_bar,wp_psi,
       bp_bar,bp_psi,min_bend_radius_mm,safety_factor)
      VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`;

    for (const h of ALL_HOSES) {
      await db.runAsync(hoSql, [
        h.hose_name, h.reinforcement??null, h.tube_material??null,
        h.temp_range??null, h.application??null,
        h.dash_size, h.id_mm??null, h.id_inch??null, h.od_mm??null,
        h.wp_bar??null, h.wp_psi??null, h.bp_bar??null, h.bp_psi??null,
        h.min_bend_radius_mm??null, h.safety_factor??null,
      ]);
    }
  });
}

